spring:

  # h2 database의 console을 확인할 수 있도록 enabled 설정
  h2:
    console:
      enabled: true

  datasource:
    url: jdbc:h2:mem:testdb;NON_KEYWORDS=USER
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop # SeesionFactory가 시작될 때 Drop, Create, Alter / 종료 시 Drop
    properties:
      hibernate: # Console에서 sql을 확인하기 위한 작업
        format_sql: true
        show_sql: true
    defer-datasource-initialization: true

jwt:
  header: Authorization
  # HS512 알고리즘을 사용할 것이기 때문에 512bit, 즉 64byte 이상의 secret key를 사용해야 한다.
  # mac : echo '<secert-key-value>'|base64
  # windows : certutil -encode <secert-key-text>.txt <secert-result-encode>.b64
  secret: ZGFuZy1oeWVvbmEtc3ByaW5nLWJvb3Qtand0LXR1dG9yaWFsLXNlY3JldC1rZXktdmFsdWUtZGF0YS10ZXN0LXByb2plY3QtdmFsdWU=
  # decode : dang-hyeona-spring-boot-jwt-tutorial-secret-key-value-data-test-project-value
  token-validity-in-seconds: 86400

logging:
  level:
    me.silvernine: DEBUG